### ISSUE TITLE
Vite / Svelte build error with design-system lib

### ISSUE THREAD

**Issue by tsukhu** [pinser-metaverse/metaverse-boostrap#1]
I am trying to port the metaverse app to svelte and running into an issue with the design-system lib
```
Could not resolve "../common/icon.element.ts"
```

- To reproduce clone the project [https://github.com/tsukhu/pinser-svelteverse](https://github.com/tsukhu/pinser-svelteverse)
- And run the following command

```
$ nx serve svelteverse

> nx run svelteverse:serve

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
X [ERROR] Could not resolve "../common/icon.element.ts"

    node_modules/@pinser-metaverse/design-system/src/lib/elements/menu/menu-button-image.element.js:5:8:
      5 │ require("../common/icon.element.ts");
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:1566
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@pinser-metaverse/design-system/src/lib/elements/menu/menu-button-image.element.js:5:8: ERROR: Could not resolve "../common/icon.element.ts"
    at failureErrorWithLog (D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:1566:15)
    at D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:1022:7)
    at D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (D:\workspace\pinser-svelteverse\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 8,
        file: 'node_modules/@pinser-metaverse/design-system/src/lib/elements/menu/menu-button-image.element.js',
        length: 27,
        line: 5,
        lineText: 'require("../common/icon.element.ts");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../common/icon.element.ts"'
    }
  ],
  warnings: []
}


```

- When I check the file file: 'node_modules/@pinser-metaverse/design-system/src/lib/elements/menu/menu-button-image.element.js', it seems to be referring to a ../common/icon.element.ts file 
```
"use strict";
exports.MenuButtonImage = void 0;
var swcHelpers = require("@swc/helpers");
var _core = require("@pinser-metaverse/core");
require("../common/icon.element.ts"); <- HERE
,,

**Comment by marcbuils** [comment]
Hi @tsukhu,
There is a problem with your build :
 node_modules/@pinser-metaverse/design-system/src/lib/elements/menu/menu-button-image.element.js:5:8
 
Your build shouldn't embedded the @pinser-metaverse dependencies because they must load in external ESM (in asynchronous)

**Comment by tsukhu** [comment]
thats true .. not a problem with pinser here .. so closing the issue
